config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale
  post 'open_ai/submit'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'articles#index'
  resources :articles do
    resource :bookmarks, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  resources :applicants
  resources :users

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure', as: :failure
  get '/auth/logout' => 'auth0#logout', as: :log_out
end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id                :bigint           not null, primary key
#  body              :text
#  user_id           :bigint           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  impressions_count :integer          default(0)
#  start_time        :datetime
#  end_time          :datetime
#
class Article < ApplicationRecord
  belongs_to :user
  has_many :applicant_articles
  has_many :applicant, through: :applicant_articles

  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :category_articles
  has_many :categories, through: :category_articles, dependent: :destroy

  is_impressionable counter_cache: true, unique: true
  has_one_attached :file

  accepts_nested_attributes_for :applicant, reject_if: :all_blank, allow_destroy: true

  def liked_by?(user)
    likes.where(user_id: user).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  load_and_authorize_resource

  impressionist actions: [:show]

  before_action :set_article, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destory]

  # GET /articles
  def index
    @articles = Article.all.order('start_time DESC').page(params[:page]).per(20)
    @number_of_articles = @articles.count
    @user = current_user
  end

  # GET /articles/1
  def show
    ActiveStorage::Current.host = 'http://localhost:3000'

    impressionist(@article)
    @article.impressionist_count(filter: :ip_address)
    @user = @article.user
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit!
    # params.require(:article).permit(:user_id, :body, :start_time, :end_time, person_ids: [], applicant_attributes: [:id, :name, :_destroy])
  end

  def correct_user
    @user = User.find(@article.user.id)
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="card article-card">
  <div class="card-body">
    <h5 class="card-title px-2"><%= article.start_time&.strftime('%Y年%m月%d日') %></h5>
    <div class="card-body">
      <div class="row">
        <div class="col-md-7">
          <h1 class="card-title"><%= article.title %></h1>
          <p class="card-text"><strong>勤務地:</strong> <%= article.work_location %></p>
          <p class="card-text"><strong>給与詳細:</strong> <%= article.salary_details %></p>
          <p class="card-text"><strong>言語要件:</strong> <%= article.language_requirement %></p>
          <p class="card-text"><strong>日本語レベル:</strong> <%= article.japanese_level %></p>
          <p class="card-text"><strong>雇用形態:</strong> <%= article.employment_type %></p>
          <p class="card-text"><strong>勤務時間:</strong> <%= article.work_hours %></p>
          <p class="card-text"><strong>試用期間:</strong> <%= article.trial_period %></p>
          <p class="card-text"><strong>休日:</strong> <%= article.days_off %></p>
          <p class="card-text"><strong>残業:</strong> <%= article.overtime %></p>
          <p class="card-text"><strong>交通手段:</strong> <%= article.transportation %></p>
          <p class="card-text"><strong>勤務環境:</strong> <%= article.work_environment %></p>
          <p class="card-text"><strong>その他手当:</strong> <%= article.other_allowances %></p>
          <p class="card-text"><strong>保険:</strong> <%= article.insurance %></p>
          <p class="card-text"><strong>その他福利厚生:</strong> <%= article.other_benefits %></p>
          <p class="card-text"><strong>説明:</strong> <%= article.description %></p>
          <p class="card-text"><strong>本文:</strong> <%= article.body %></p>

          <% if current_user?(@user) %>
            <div class="row mt-4">
              <div class="col-md-6 text-center">
                <%= link_to "Edit", edit_article_path(article), class:"btn btn-primary" %>
              </div>
              <div class="col-md-6 text-center">
                <%= button_to "Destroy", article, method: :delete, class:"btn btn-danger", data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          <% else %>
          <% if false %>
            <div class="row mt-4">
              <div class="col-md-12 text-center">
                <%= render "/articles/like" %>
                <%= render "/articles/bookmark" %>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>
        <div class="col-md-5">
          <% if article.file.attached? %>
            <%= image_tag article.file, style: "max-width: 100%; max-height: 100%;" %>
          <% else %>
            <img src="<%= asset_path('World-14.png') %>" alt="Matches Logo" style="flex: 1; width: auto; max-width: 100%;">
          <% end %>
        </div>
      </div>
    </div>
    <div>

    <div class="text-left pb-1">
    </div>
  </div>
</div>

app/views/articles/_articles_list.html.erb
<div class="row" id="articles">
  <% articles.each do |article| %>
    <div class="col-sm-12 mb-3">
      <%= render "articles/article", article: article %>
    </div>
  <% end %>
</div>
  <% if @user %>
    <%= paginate articles %>
  <% end %>

app/views/articles/_bookmark.html.erb
  <% if @article.bookmarked_by?(current_user) %>
    <%= link_to article_bookmarks_path(@article), class: "px-2", style:"text-align: right; color: black;", method: :delete do %>
      <i class="fa-solid fa-bookmark fa-2x"></i>
    <% end %>
  <% else %>
    <%= link_to article_bookmarks_path(@article), class: "px-2", style:"text-align: right; color: black;", method: :post do %>
      <i class="fa-regular fa-bookmark fa-2x"></i>
    <% end %>
  <% end %>

app/views/articles/_form.html.erb
<div class="card create-new">
  <div class="card-header">
    <h5 class="card-title">新規作成</h5>
  </div>
  <div class="card-body">
    <%= form_with(model: article) do |form| %>
      <% if article.errors.any? %>
        <div class="alert alert-danger">
          <h6><%= pluralize(article.errors.count, "error") %> が保存を妨げました:</h6>
          <ul>
            <% article.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :start_time, class: "form-label" %>
        <%= form.date_field :start_time, class: "form-control", value: Date.today %>
      </div>

      <div class="mb-3">
        <%= form.label :body, class: "form-label" %>
        <%= form.text_area :body, class: "form-control", style: "height: 200px;" %>
      </div>
  
      <div class="mb-3">
        <%= form.label :file, class: "form-label" %>
        <%= form.file_field :file, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :application_deadline, class: "form-label" %>
        <%= form.date_field :application_deadline, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :salary_details, class: "form-label" %>
        <%= form.text_area :salary_details, class: "form-control", style: "height: 200px;" %>
      </div>

      <div class="mb-3">
        <%= form.label :work_location, class: "form-label" %>
        <%= form.text_field :work_location, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :language_requirement, class: "form-label" %>
        <%= form.text_field :language_requirement, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :japanese_level, class: "form-label" %>
        <%= form.text_field :japanese_level, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :skills_required, class: "form-label" %>
        <%= form.text_area :skills_required, class: "form-control", style: "height: 200px;" %>
      </div>

      <div class="mb-3">
        <%= form.label :employment_type, class: "form-label" %>
        <%= form.text_field :employment_type, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, class: "form-control", style: "height: 200px;" %>
      </div>

      <div class="mb-3">
        <%= form.label :work_hours, class: "form-label" %>
        <%= form.text_field :work_hours, class: "form-control" %>
      </div>

      <div class="d-grid">
        <%= form.submit '保存', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_like.html.erb
  <% if @article.liked_by?(current_user) %>
    <%= link_to article_likes_path(@article), method: :delete, style: "color: black;" do %>
      <i class="fa-solid fa-thumbs-up fa-2x"></i>
    <% end %>
  <% else %>
    <%= link_to article_likes_path(@article), method: :post, style: "color: black;" do %>
      <i class="fa-regular fa-thumbs-up fa-2x"></i>
    <% end %>
  <% end %>

app/views/articles/_people.html.erb
<div class="card">
    <div class="card-title mt-3">
        <h4>I will meet</h4>
    </div>
    <div class="card-title mt-3">
        <h4>I recently met</h4>
    </div>
    <div class="card-body">
        <p class="card-text">
            <% @applicant.each do |person| %>
            <%= person.name %><br>
            <% end %>
        </p>
    </div>
</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>
<br>

app/views/articles/index.html.erb
<div style="display: flex; align-items: center; padding: 2px; text-align: center;">
  <h1 class="header-title d-none d-lg-block slide-in"><%= t('header.title.full') %></h1>
  <h1 class="header-title d-lg-none" style="margin-bottom: 10px;"><%= t('header.title.short') %></h1>
  <img src="<%= asset_path('World-10.png') %>" alt="<%= t('header.title.full') %>" class="logo-image">
</div>

<div class="benefits">
  <h2><%= t('global_career_support.service_benefits.section_title') %></h2>
  <ul>
      <li><strong><%= t('global_career_support.service_benefits.income_opportunity.title') %>:</strong> <%= t('global_career_support.service_benefits.income_opportunity.description') %></li>
      <li><strong><%= t('global_career_support.service_benefits.language_support.title') %>:</strong> <%= t('global_career_support.service_benefits.language_support.description') %></li>
      <li><strong><%= t('global_career_support.service_benefits.future_career.title') %>:</strong> <%= t('global_career_support.service_benefits.future_career.description') %></li>
  </ul>
  <p class="d-none d-md-block"><%= t('global_career_support.service_benefits.summary') %></p>
  <% if current_user %>
    <div style="text-align: center;">
      <%= button_to t('resume.upload'), user_path(current_user), method: :get, style: "padding: 12px 30px; font-size: 16px; background-color: #4285F4; color: white; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
    </div>
  <% else %>
    <div style="text-align: center;">
      <%= button_to t('resume.upload'), '/auth/auth0', method: :post, data: { turbo: false }, style: "padding: 12px 30px; font-size: 16px; background-color: #4285F4; color: white; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
    </div>
  <% end %>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="service-card text-center">
        <%= image_tag("resume_icon.jpg", alt: t('services.ai_review'), class: "img-fluid") %>
        <h3><%= t('services.ai_review') %></h3>
        <p><%= t('services.ai_review_description') %></p>
      </div>
    </div>
    <div class="col-md-4 mb-4">
      <div class="service-card text-center">
        <%= image_tag("recruiter_icon.jpg", alt: t('services.recruiter_support'), class: "img-fluid") %>
        <h3><%= t('services.recruiter_support') %></h3>
        <p><%= t('services.recruiter_support_description') %></p>
      </div>
    </div>
    <div class="col-md-4 mb-4">
      <div class="service-card text-center">
        <%= image_tag("visa_support_icon.jpg", alt: t('services.visa_support'), class: "img-fluid") %>
        <h3><%= t('services.visa_support') %></h3>
        <p><%= t('services.visa_support_description') %></p>
      </div>
    </div>
  </div>
</div>

<style>
  .slide-in {
    transform: translateY(-30px);
    opacity: 0;
    animation: slideIn 1s ease-out forwards;
  }

  @keyframes slideIn {
    to {
      transform: translateY(0);
      opacity: 1;
    }
  }

  .service-card {
    border: 1px solid #ddd;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s, box-shadow 0.3s;
    padding: 20px;
  }

  .service-card img {
    height: auto;
  }
  .service-card h3 {
    margin-top: 15px;
    font-size: 1.25rem;
    color: #333;
  }
  .service-card p {
    color: #333;
  }

  .benefits {
      background-color: #f9f9f9;
      padding: 20px;
      border-radius: 8px;
      margin-top: 30px;
  }
  .benefits h2 {
      color: #4285F4;
  }
  .benefits ul {
      list-style-type: none;
      padding-left: 0;
  }
  .benefits li {
      margin-bottom: 15px;
      padding-left: 25px;
      position: relative;
  }
  .benefits li::before {
      content: '✓';
      color: #4285F4;
      position: absolute;
      left: 0;
      top: 0;
  }
</style>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<div class="container-sm"> <!-- containerをcontainer-smに変更 -->
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center" style="background-color: blue; color: white;">
      <%= notice %>
    </div>
    <%= render "article", article: @article %>
    <div class="card-footer text-center">
      <a href="#" class="btn" style="background-color: #FF5733; color: white">応募する</a>
      <br>
      <i class="fas fa-eye"></i> <%= @article.impressionist_count(:filter=>:ip_address) %>
    </div>
  </div>
</div>