config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale
  post 'open_ai/submit'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'articles#index'
  resources :articles do
    resource :bookmarks, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  resources :applicants
  resources :users

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure', as: :failure
  get '/auth/logout' => 'auth0#logout', as: :log_out
end

app/models/applicant.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: Applicants
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  creater_id :integer          not null
#
class Applicant < ApplicationRecord
  has_many :applicant_articles
  has_many :articles, through: :applicant_articles
  has_one :user, as: :rolable, dependent: :destroy

  has_many_attached :files
end

app/controllers/applicants_controller.rb
# frozen_string_literal: true

# app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  load_and_authorize_resource

  before_action :set_applicant, only: %i[show edit update destroy]

  # GET /applicants
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  def show; end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit; end

  # POST /applicants
  def create
    @applicant = Applicant.new(applicant_params)

    if @applicant.save
      redirect_to @applicant, notice: 'Applicant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /applicants/1
  def update
    if @applicant.update(applicant_params)
      if @applicant.files.attached?
        begin
          analyzer = ResumeAnalyzerService.new(@applicant.files.last)
          @improvement_suggestions = analyzer.analyze_resume
          flash[:success] = '履歴書がアップロードされ、分析が完了しました。'
          @user = @applicant.user
          render 'users/show'
        rescue StandardError => e
          flash[:alert] = "エラーが発生しました: #{e.message}"
          render :edit, status: :unprocessable_entity
        end
      else
        flash[:alert] = '履歴書が添付されていません。'
        render :edit, status: :unprocessable_entity
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /applicants/1
  def destroy
    @applicant.destroy
    redirect_to applicants_url, notice: 'Applicant was successfully destroyed.', status: :see_other
  end

  private

  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  def applicant_params
    params.require(:applicant).permit(:name,
                                      :user_id,
                                      :creater_id,
                                      :birthday,
                                      :age,
                                      :nationality,
                                      :phone_number,
                                      :self_introduction,
                                      :desired_salary,
                                      :resume,
                                      files: [])
  end
end

app/helpers/applicants_helper.rb
# frozen_string_literal: true

module ApplicantsHelper
end

app/views/applicants/_applicant.html.erb
<div id="<%= dom_id applicant %>">
</div>

app/views/applicants/_form.html.erb
<%= form_with(model: applicant, class: "needs-validation", novalidate: true) do |form| %>
  <% if applicant.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">Oops! <%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h4>

      <ul>
        <% applicant.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :birthday, class: "form-label" %>
    <%= form.date_field :birthday, class: "form-control" %>
  </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :files, class: "form-label" %>
    <%= form.file_field :files, multiple: true, class: "form-control" %>
  </div>

  <%if false %>
  <div class="mb-3">
    <%= form.label :nationality, class: "form-label" %>
    <%= form.number_field :nationality, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone_number, class: "form-label" %>
    <%= form.number_field :phone_number, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :self_introduction, class: "form-label" %>
    <%= form.text_area :self_introduction, class: "form-control", rows: 5 %>
  </div>

  <div class="mb-3">
    <%= form.label :desired_salary, class: "form-label" %>
    <%= form.text_area :desired_salary, class: "form-control", rows: 5 %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<div class="container">
  <h1 class="mb-4">Editing Applicant</h1>

  <div class="card">
    <div class="card-body">
      <%= render "form", applicant: @applicant %>
    </div>
  </div>

  <div class="mt-4">
    <%= link_to "Show this applicant", @applicant, class: "btn btn-primary mr-2" %>
    <%= link_to "Back to applicants", applicants_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/applicants/index.html.erb
<div style="display: flex; align-items: center; padding: 2px; text-align: center;">
  <h1 class="header-title">Working with Foreigners</h1>
  <img src="<%= asset_path('World-10.png') %>" alt="Matches Logo" class="logo-image">
</div>

<div class="row">
  <% @applicants.each do |applicant| %>
    <div class="col-sm-4 mb-4">
      <div class="card">
        <div class="card-header d-flex justify-content-end">
          <% if applicant.user&.avatar&.attached? %>
            <img src="<%= url_for(applicant.user&.avatar) %>" alt="Applicant Image" style="flex: 1; width: auto; max-width: 100%;">
          <% else %>
            <img src="<%= asset_path('World-14.png') %>" alt="Default Image" style="flex: 1; width: auto; max-width: 100%;">
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= applicant.name %></h5>
          <p class="card-text">年齢: <%= applicant.age %></p>
          <p class="card-text">国籍: <%= applicant.nationality %></p>
          <p class="card-text">自己紹介: <%= applicant.self_introduction %></p>
          <%= link_to "詳細を見る", applicant, class: "btn btn-primary" %>
          <% if applicant.user&.admin? %>
            <div class="col-sm-8 m-8">
              <div class="personal-details">
                <% if applicant.files.attached? %>
                  <hr style="border: 1px solid black;">
                  <% applicant.files.each do |file| %>
                    <p>
                      <%= link_to "#{file.filename}", rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary" %>
                    </p>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/applicants/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Fill in the form below to apply for a job.</h2>
    <p>You can write in your mother tongue.</p>
    <%= render "form", applicant: @applicant %>
    <br>
  </div>
  <div class="col-md-6">
    <h2>Resume in Japanese</h2>
    <p>AIにより自動翻訳された履歴書です</p>
  </div>
</div>

<div>
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/show.html.erb
<div class="container">
  <!-- Notification -->
  <p class="notice"><%= notice %></p>
  <%= link_to "Back", applicants_path, class: "btn btn-secondary" %>
  <!-- Profile Card -->
  <div class="card profile-card">
    <div class="card-body profile-body">
      <div class="row">
        <div class="col-sm-4 mb-4">
                <% if @applicant.user&.avatar&.attached? %>
                  <%= image_tag(@applicant.user&.avatar, alt: "Applicant Image", style: "flex: 1; width: 100%;") %>
                <% else %>
                  <img src="<%= asset_path('World-14.png') %>" alt="Default Image" style="flex: 1; width: auto; max-width: 100%;">
                <% end %>
            <div class="profile-details">
              <div class="profile-header">
                <h1 class="profile-name"><%= @applicant.name %></h1>
                <div class="profile-actions">
                  <%= link_to "Apply", applicant_path(@applicant), class: "btn btn-success", id: "apply-button", data: { confirm: "申し込みました" } %>
                  <% if false %><%= link_to "Chat", applicants_path, class: "btn btn-outline-primary" %><% end %>
                </div>
              </div>
            </div>

            <div class="profile-tabs">
              <p class="card-text"><strong>Birthday:</strong> <%= @applicant.birthday %></p>
              <p class="card-text"><strong>Age:</strong> <%= @applicant.age %></p>
              <p class="card-text"><strong>Nationality:</strong> <%= @applicant.nationality %></p>
              <p class="card-text"><strong>Phone Number:</strong> <%= @applicant.phone_number %></p>
              <p class="card-text"><strong>Self Introduction:</strong> <%= @applicant.self_introduction %></p>
              <p class="card-text"><strong>Desired Salary:</strong> <%= @applicant.desired_salary %></p>
            </div>
            <% if current_user?(@applicant.user_id) %>
              <div>
                <%= link_to "Edit", edit_applicant_path(@applicant), class: "btn btn-primary mr-2" %>
              </div>
              <div>
                <%= button_to "Destroy", @applicant, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              </div>
            <% end %>
            <% if @applicant.user&.admin? %>
            <div class="col-sm-8 mb-8">
              <div class="personal-details">
                <% if @applicant.files.attached? %>
                  <% @applicant.files.each do |file| %>
                    <p>
                      <%= link_to "#{file.filename}", rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary" %>
                    </p>
                  <% end %>
                <% else %>
                  <p>ファイルが添付されていません。</p>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

<style>
.profile-header {
  display: flex;
  align-items: center;
}

.profile-name {
  margin-right: 20px; /* ボタンと名前の間にスペースを追加 */
}

.profile-actions {
  display: flex;
  gap: 10px; /* ボタン同士の間にスペースを追加 */
}
</style>