config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale
  post 'open_ai/submit'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'articles#index'
  resources :articles do
    resource :bookmarks, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end

  resources :applicants
  resources :users

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure', as: :failure
  get '/auth/logout' => 'auth0#logout', as: :log_out
end

app/views/layouts/_footer.html.erb
<footer class="footer-container">
   <hr style="border: 1px solid black;">
  <div class="language-selector">
    <%= link_to 'English', switch_locale_path(locale: 'en') %>
    &nbsp;
    <%= link_to '日本語', switch_locale_path(locale: 'ja') %>
    &nbsp;
    <%= link_to 'Tiếng Việt', switch_locale_path(locale: 'vi') %>
    &nbsp;
    <%= link_to 'বাংলা', switch_locale_path(locale: 'bn') %>
    &nbsp;
    <%= link_to 'မြန်မာစာ', switch_locale_path(locale: 'my') %>
    &nbsp;
    <%= link_to 'Русский', switch_locale_path(locale: 'ru') %>
  </div>
  <br />
    <%= link_to 'Terms of use', page_path('terms') , class: "m-4" %>
    <%= link_to 'Privacy Policy', page_path('policy') , class: "m-4" %>
    <%= link_to 'Internship', page_path('internship') , class: "m-4" %>
    <%= link_to 'About Us', page_path('about') , class: "m-4" %>
    <%= link_to 'Contact', page_path('contact') , class: "m-4" %>
  <br />
  <br />
    © 2024 Copyright:
    <a class="footer-link" href="https://job-in-japan.com/">Job in Japan</a>
    </br>
    <% unless Rails.env.production? %>
      <% if current_user&.admin? %>
        <%= link_to "admin", rails_admin.dashboard_path %>
      <% elsif current_user&.employee? %>
        <p>Employee</p>
      <% elsif current_user&.applicant? %>
        <p>Applicant</p>
      <% else %>
        <p>Guest</p>
      <% end %>
    <% end %>
  <br />
</footer>

<style>
  .footer-container {
    text-align: center;
    color: black;
    position: relative;
    min-height: 5vh;
  }
</style>

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-CG668SBN9T"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-CG668SBN9T');
</script>

app/views/layouts/_header.html.erb
<header class="header-container">
  <%= link_to "Job in Japan", root_path, class: "header-title-link" %>

  <div class="header-links">
    <% if current_page?(root_path) %>
      <%= link_to t('hiring_companies_here'), applicants_path, class: "header-link" %>
    <% else %>
      <%= link_to t('job_seekers_click_here'), root_path, class: "header-link" %>
    <% end %>

    <% if current_user %>
      <div class="user-info">
        <%= link_to user_path(current_user.id), class: "header-link user-icon-link" do %>
          <i class="fas fa-user-circle user-icon"></i>
        <% end %>
      </div>
      <% if false %>
      <div class="notification-bell">
        <i class="fas fa-bell"></i>
        <span class="notification-badge">0</span>
      </div>
      <% end %>
    <% else %>
      <div class="login-button">
        <%= button_to t('login'), '/auth/auth0', method: :post, data: { turbo: false }, class: "button-modern" %>
      </div>
    <% end %>
  </div>
</header>

<style>
  .header-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 30px; 
    background: linear-gradient(135deg, #8aafed, #e0f0ff);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-bottom: 1px solid #e1e1e1;
    margin-top: 20px;
    margin-bottom: 20px;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2); 
  }

  .header-title-link {
    font-size: 28px;
    font-weight: bold;
    color: #fff;
    text-decoration: none;
    transition: color 0.3s;
  }

  .header-title-link:hover {
    color: #007bff;
  }

  .header-links {
    display: flex;
    align-items: center;
  }

  .header-link {
    margin-left: 20px;
    font-size: 20px;
    color: #007bff;
    text-decoration: none;
    transition: color 0.3s;
  }

  .header-link:hover {
    color: #007bff;
  }

  .user-info {
    display: flex;
    align-items: center;
    margin-left: 20px; /* アイコンの左マージン */
  }

  .user-icon-link {
    text-decoration: none;
    color: #000;
    font-size: 24px; /* アイコンのサイズを調整 */
    margin-left: 0; /* アイコンを左に移動させるマージンを削除 */
  }

  .user-icon {
    transition: color 0.3s;
  }

  .user-icon-link:hover .user-icon {
    color: #007bff; /* ホバー時の色を調整 */
  }

  .logout-button, .login-button {
    margin-left: 20px;
  }

  .button-modern {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    font-size: 14px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .button-modern:hover {
    background-color: #0056b3;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job in Japan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6034033690905779" crossorigin="anonymous"></script>
  </head>

  <body class="pastel-blue-gradient">
    <div class="container main-container">
      <%= render "layouts/header" %>
      <%= content_tag(:div, flash[:alert], class: "alert alert-danger") if flash[:alert] %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>